### ISSUE TITLE
Brightness values got reset after every reboot

### ISSUE THREAD

**Issue by HeikoAdams** [nailfarmer/gnome-shell-dim-on-battery-extension#7]
When modifying the brightness values they got reset after every reboot which sucks

**Comment by nailfarmer** [comment]
Sorry for not responding sooner.  Do you know what distribution and what version of gnome-shell you're running?

**Comment by HeikoAdams** [comment]
I'm running Gnome 3.20 on Fedora 24

**Comment by killarny** [comment]
This extension doesn't seem to really work properly on 3.20 - so far in my experience it seems to be changing the AC power setting to some value near what the battery power setting is. Near it, though, not exactly the same.

For example, I have the battery brightness set to 20%, and I will set the AC power brightness to 100%. This works until I turn the power off, and then the AC power brightness setting will somehow get changed to 19% until I open the config and fix it.

*Edited for clarity

**Oh, also I'm using UbuntuGNOME 16.04, with the Gnome 3.20 staging ppa activated.

**Comment by nailfarmer** [comment]
Thanks for the additional input!  If you have the time to test, I've pushed a change to the repo that fixes this for me in 3.20.  It should be up on the e.g.o website within a day or so, just waiting to have it reviewed.

**Comment by HeikoAdams** [comment]
The issue is still present in latest version and can be reproduced very easy: Set the battery value to 50% while notebook runs on battery -> close config window -> disable and enable extension a few times. Every time you disable or enable the extension the brightnes gets reduced until its value is at 11%

**Comment by nailfarmer** [comment]
Thanks @HeikoAdams, that was incredibly helpful. I've been having trouble consistently triggering this behavior.

If you have the time, can you please see if the latest changes to master fix this for you?

Cheers.

**Comment by HeikoAdams** [comment]
No, the behaviour is still present in latest git master

**Comment by Th3Z0ne** [comment]
As of gnome-shell 3.24.2 I can - not - confirm that behavior. Only thing is that when you change your brightness manually (weather it be on AC or DC) it will remember that. - but that is intentionally judging from the code.
